### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by chirag4582**
Added [Schema](https://drive.google.com/file/d/1LRq9cwAHNFE3EyCQFS0OQ1qeWCF9OmMP/view?usp=drive_link) and [Erd](https://drive.google.com/file/d/1fEVe5vuL47tG-emAV7Z2gulSJmIu5iEu/view?usp=drive_link) 

Here is an explanation on [loom](https://www.loom.com/share/6bf841e257b84c93bf2dc11aa6d36be9?sid=87fed676-52b6-4e61-9841-b6602f33e94d)

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
1. ERD is not proper with pets entity, the attributes of pets should be connected to the entity,
2. In Schema 
     Missing with role_id foreign key connection from Adopters to Role table.
     Adoption_requests table is missing with adopter_id that should be connected as foreign key.
     No need of shetler_id in adoption_requests table, as pet_id already has its shelter connection.

**Comment by chirag4582** [comment]
I changed the erd
https://drive.google.com/file/d/1hvf0GJY7s0yCuboOBE4l_h4DRYt2ezym/view?usp=sharing
and also removed shetler_id in adoption_requests table

**Comment by PRASANNAPATHI** [comment]
ERD is ok,
But what about schema diagram, that I have mentioned in the comment?
Please update and submit the schema diagram too.

**Comment by chirag4582** [comment]
https://drive.google.com/file/d/1HuQ5xo1zW6S0Hhjvhvy8bV0tGLRGxPck/view?usp=sharing

made recommended changes to schema diagram

**Comment by PRASANNAPATHI** [comment]
your drive link is private accessible,
Please make it public access

**Comment by chirag4582** [comment]
it's public now

**Comment by PRASANNAPATHI** [comment]
Still now, there are some changes pending as per the comment.

Can you please book a slot in my calendar for viva.

**Comment by chirag4582** [comment]
https://drive.google.com/file/d/1yq-Xsy1ag5OtIYVIiyl3avrTJnZsJy4d/view?usp=sharing
This is the updated schema with all changes made. Do have a look

**Comment by chirag4582** [comment]
https://drive.google.com/file/d/1G2oit7O6mIzjAq3_aq9wY4WNisSMCqTF/view?usp=sharing
this is the updated erd with cardinality added

**Comment by PRASANNAPATHI** [comment]
Approved in viva,

Please, merge it now for Schema & ERD.

**Pull request merged**
